# Generated by Django 3.2 on 2021-07-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0002_createpoll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpoll',
            name='description',
        ),
    ]
