# Generated by Django 3.2 on 2021-07-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0003_remove_createpoll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PollApp.register'),
        ),
    ]
